name: Linux

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Ubuntu 18.04
    runs-on: ubuntu-latest

    env:
      GIT: "https://github.com"
      CMAKE_VER: "3.18.4"
      REPO_NAME: "2048-rpg"
      LIB_PATH: "/var/temp"
      MANUAL_CACHING: "6"
      AUTO_CACHING: "1"

    steps:

      - name: Clone. 🛎️
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: First set up. 🛠
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
          build-essential clang git wget autoconf python-minimal g++ libgdk-pixbuf2.0-dev \
          python-pip libx11-dev libxmu-dev libglu1-mesa-dev libgl2ps-dev libxi-dev libzip-dev \
          libpng-dev libcurl4-gnutls-dev libfontconfig1-dev libsqlite3-dev libglew-dev \
          libssl-dev libgtk-3-dev libglfw3 libglfw3-dev xorg-dev cmake

      - name: Setup vars
        shell: bash
        run: |
          if test -z "{{ EVENT_PAYLOAD.pull_request.html_url }}"
          then
            echo "BUILD_PULL_REQUEST_TEXT=''" >> $GITHUB_ENV
          else
            echo "BUILD_PULL_REQUEST_TEXT='Pull request - {{ EVENT_PAYLOAD.pull_request.html_url }}'" >> $GITHUB_ENV
          fi

      - name: Build. 🔨
        shell: bash
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ../
          make -j 4
          echo "BUILD_SUCCESS=true" >> $GITHUB_ENV
#          make test todo

      - name: Discord succes notification
        if: env.BUILD_SUCCESS == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '✅[SUCCESS](Linux Tests) The project {{ EVENT_PAYLOAD.repository.full_name }} has been built.'

      - name: Discord fail notification
        if: env.BUILD_SUCCESS != 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '❌[FAIL](Linux Tests) The project {{ EVENT_PAYLOAD.repository.full_name }} was built with errors.'
